apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: app1-workload
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: app1-workload
spec:
  source:
    git:
      url: https://github.com/ignaciylipm/app1-workload.git
      ref:
        branch: main
