apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app2-workload
  description: App2 worker App
  tags:
    - java
    - nosql
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=app2-workload,tier=cache'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ipm-team
  system: App2-workload-system
  dependsOn: [Component:yelb-db]